<a href="https://colab.research.google.com/github/melvintijo/ADS_Projekt_FMS/blob/master/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import random
import pickle
import time

In [2]:
DIRECTORY = r'C:\Users\sarum\ADS_Project_FiMeSi\ADS_Projekt_FMS\Pictures'
CATEGORIES = ['Cats','Dogs']

In [3]:
# IMG_SIZE = 50 #< bereits erledigt oder? - NR. 3

data = [] # NR. 4

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    print(folder)
    label = CATEGORIES.index(category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        # print(img_path) #< zur Kontrolle NR. 1
        # break #< zur Kontrolle NR. 1
        img_array = cv2.imread(img_path)
        # img_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE)) #< bereits erledigt oder? - NR. 3
        data.append([img_array, label]) # NR. 4
        # plt.imshow(img_array) #< zur Kontrolle - NR. 2, evtl. (img_array, , cmap = 'gray')
        # break #< zur Kontrolle NR. 2

C:\Users\sarum\ADS_Project_FiMeSi\ADS_Projekt_FMS\Pictures\Cats
C:\Users\sarum\ADS_Project_FiMeSi\ADS_Projekt_FMS\Pictures\Dogs


In [4]:
len(data)

375

In [5]:
random.shuffle(data)

In [6]:
data[0]

[array([[[255, 255, 255],
         [212, 212, 212],
         [182, 182, 182],
         ...,
         [182, 182, 182],
         [215, 215, 215],
         [255, 255, 255]],
 
        [[230, 230, 230],
         [149, 149, 149],
         [101, 101, 101],
         ...,
         [105, 105, 105],
         [152, 152, 152],
         [225, 225, 225]],
 
        [[191, 191, 191],
         [ 91,  91,  91],
         [ 39,  39,  39],
         ...,
         [ 46,  46,  46],
         [ 94,  94,  94],
         [179, 179, 179]],
 
        ...,
 
        [[156, 156, 156],
         [103, 103, 103],
         [ 79,  79,  79],
         ...,
         [ 41,  41,  41],
         [ 84,  84,  84],
         [157, 157, 157]],
 
        [[191, 191, 191],
         [134, 134, 134],
         [102, 102, 102],
         ...,
         [ 87,  87,  87],
         [137, 137, 137],
         [211, 211, 211]],
 
        [[242, 242, 242],
         [182, 182, 182],
         [146, 146, 146],
         ...,
         [135, 135, 135],
  

In [7]:
X = [] #features
y = [] #labels

for features, labels in data:
    X.append(features)
    y.append(labels)

In [8]:
X = np.array(X)
y = np.array(y)

In [9]:
len(X)

375

In [10]:
len(y)

375

In [11]:
pickle.dump(X, open('X.pkl', 'wb'))
pickle.dump(y, open('y.pkl', 'wb'))      

In [12]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [13]:
X

array([[[[255, 255, 255],
         [212, 212, 212],
         [182, 182, 182],
         ...,
         [182, 182, 182],
         [215, 215, 215],
         [255, 255, 255]],

        [[230, 230, 230],
         [149, 149, 149],
         [101, 101, 101],
         ...,
         [105, 105, 105],
         [152, 152, 152],
         [225, 225, 225]],

        [[191, 191, 191],
         [ 91,  91,  91],
         [ 39,  39,  39],
         ...,
         [ 46,  46,  46],
         [ 94,  94,  94],
         [179, 179, 179]],

        ...,

        [[156, 156, 156],
         [103, 103, 103],
         [ 79,  79,  79],
         ...,
         [ 41,  41,  41],
         [ 84,  84,  84],
         [157, 157, 157]],

        [[191, 191, 191],
         [134, 134, 134],
         [102, 102, 102],
         ...,
         [ 87,  87,  87],
         [137, 137, 137],
         [211, 211, 211]],

        [[242, 242, 242],
         [182, 182, 182],
         [146, 146, 146],
         ...,
         [135, 135, 135],
        

In [18]:
X = X/255

In [19]:
X

array([[[[1.53787005e-05, 1.53787005e-05, 1.53787005e-05],
         [1.27854294e-05, 1.27854294e-05, 1.27854294e-05],
         [1.09761706e-05, 1.09761706e-05, 1.09761706e-05],
         ...,
         [1.09761706e-05, 1.09761706e-05, 1.09761706e-05],
         [1.29663553e-05, 1.29663553e-05, 1.29663553e-05],
         [1.53787005e-05, 1.53787005e-05, 1.53787005e-05]],

        [[1.38709848e-05, 1.38709848e-05, 1.38709848e-05],
         [8.98598578e-06, 8.98598578e-06, 8.98598578e-06],
         [6.09117157e-06, 6.09117157e-06, 6.09117157e-06],
         ...,
         [6.33240609e-06, 6.33240609e-06, 6.33240609e-06],
         [9.16691167e-06, 9.16691167e-06, 9.16691167e-06],
         [1.35694416e-05, 1.35694416e-05, 1.35694416e-05]],

        [[1.15189482e-05, 1.15189482e-05, 1.15189482e-05],
         [5.48808528e-06, 5.48808528e-06, 5.48808528e-06],
         [2.35203655e-06, 2.35203655e-06, 2.35203655e-06],
         ...,
         [2.77419695e-06, 2.77419695e-06, 2.77419695e-06],
         [

In [21]:
X.shape

(375, 500, 500, 3)

In [22]:
y

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,

In [23]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [25]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))


In [26]:
model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [27]:
model.fit(X, y, epochs=5, validation_split=0.1)

Epoch 1/5
11/11 [==============================] - 96s 9s/step - loss: 0.7043 - accuracy: 0.5045 - val_loss: 0.6921 - val_accuracy: 0.5263
Epoch 2/5
11/11 [==============================] - 87s 8s/step - loss: 0.6929 - accuracy: 0.5252 - val_loss: 0.6927 - val_accuracy: 0.5263
Epoch 3/5
11/11 [==============================] - 93s 8s/step - loss: 0.6926 - accuracy: 0.5252 - val_loss: 0.6925 - val_accuracy: 0.5263
Epoch 4/5
11/11 [==============================] - 79s 7s/step - loss: 0.6924 - accuracy: 0.5252 - val_loss: 0.6923 - val_accuracy: 0.5263
Epoch 5/5
11/11 [==============================] - 81s 7s/step - loss: 0.6923 - accuracy: 0.5252 - val_loss: 0.6921 - val_accuracy: 0.5263


In [ ]:
# Ab hier Sublime - trainin_models.py